// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoj6O4L1Wb9ZcKJQViw7U3oe_PP-7kPzQ',
    appId: '1:201182605141:web:2345338bd6b3a7339709dc',
    messagingSenderId: '201182605141',
    projectId: 'medlab-87d1b',
    authDomain: 'medlab-87d1b.firebaseapp.com',
    storageBucket: 'medlab-87d1b.firebasestorage.app',
    measurementId: 'G-6Z1QV7YXSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQvzfXAOSMqytK2YRzbItGd4JR6Z-S7lU',
    appId: '1:201182605141:android:0cf81ce4aca7c7e09709dc',
    messagingSenderId: '201182605141',
    projectId: 'medlab-87d1b',
    storageBucket: 'medlab-87d1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXPYGLZ-XVvv8cIu00_AXJDb-Pua-UHFU',
    appId: '1:201182605141:ios:1e33a19453aa56e79709dc',
    messagingSenderId: '201182605141',
    projectId: 'medlab-87d1b',
    storageBucket: 'medlab-87d1b.firebasestorage.app',
    iosBundleId: 'com.example.medilab',
  );
}
